#! /usr/bin/env bash

function get_unused_port() {
    python -c 'import socket; s = socket.socket(socket.AF_INET, socket.SOCK_STREAM); s.bind(("", 0)); print(s.getsockname()[1]); s.close()'
}

if [[ -v $JUPYTER_PORT ]]; then
    port=$JUPYTER_PORT
else
    port=`get_unused_port`
fi

extip=`dig +short myip.opendns.com @resolver1.opendns.com`
ipnip=`hostname -i`
token=$(hexdump -n 24 -e '6/4 "%08x" 1 "\n"' /dev/urandom)

# Simple port forwarding through login node
echo -e "Run the following command on your local machine:       vvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
ssh -L $port:$ipnip:$port $extip
Notebook address
==================================================
http://localhost:${port}?token=${token}
==================================================
"

jupyter-notebook --no-browser --port=$port --ip=$ipnip --NotebookApp.token=$token
